name: 'Report Coverage'
on:
  pull_request:
    branches:
      - main
jobs:
    permissions:
        contents: write
        pull-requests: write
        checks: write
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
