name: 'Report Coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  permissions:
    checks: write
    contents: read|write|none
    pull-requests: read|write|none
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
